"""empty message

Revision ID: 0c66a5cd1b16
Revises: e1599b850cb5
Create Date: 2023-01-16 12:35:40.350778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c66a5cd1b16'
down_revision = 'e1599b850cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('clocked_in', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('manager', sa.Boolean(), nullable=False),
    sa.Column('empl_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('clocked_in', sa.BOOLEAN(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('manager', sa.BOOLEAN(), nullable=False),
    sa.Column('empl_id', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('staffs')
    # ### end Alembic commands ###
