"""empty message

Revision ID: 800035f4dbe6
Revises: 01a057cfdd80
Create Date: 2023-01-17 10:19:46.406666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800035f4dbe6'
down_revision = '01a057cfdd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=25), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('receipt_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_status', sa.Boolean(), nullable=False))

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.alter_column('table_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.alter_column('table_status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_status')

    op.create_table('receipt_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('item_price', sa.INTEGER(), nullable=False),
    sa.Column('instructions', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('receipt_orders')
    # ### end Alembic commands ###
